from Python.llm_client import OllamaClient

class EvaluatorAgent:
    """
    Evaluates a generated email for professionalism and clarity using an LLM (e.g., Phi-3)
    """

    def __init__(self, model: str = "phi3"):
        self.client = OllamaClient(model=model)

    def run(self, email_text: str) -> str:
        """
        Args:
            email_text (str): The email generated by EmailAgent

        Returns:
            str: Evaluation text from the LLM
        """
        system_prompt = (
            """You are a senior manager evaluating written communication.

Your task:
- Assess professionalism and clarity of the email

Rules:
- Provide a professionalism score out of 10
- List strengths first
- Then list improvement suggestions
- Be constructive and concise
"""
        )

        user_prompt = f"""
Email to evaluate:
\"\"\"
{email_text}
\"\"\"

Please provide:
1. Overall professionalism score (1-10)
2. Summary of strengths
3. Suggestions for improvement
Format your response in bullet points.
"""

        return self.client.generate(
            prompt=user_prompt,
            system=system_prompt,
            temperature=0.2
        )
